spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_cloud
    username: postgres
    password: vladimir
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

server:
  port: 8192
  servlet:
    context-path: /app

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetchRegistry: true