spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productsbase;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.H2Dialect

server:
  port: 8192

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}