server:
  port: 8190
#  servlet:
#    context-path: /app

spring:
  application:
    name: front-service
  mvc:
    hiddenmethod:
      filter:
        enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
