server:
  port: 8190
  servlet:
    context-path: /rest

spring:
  application:
    name: rest-template
  mvc:
    hiddenmethod:
      filter:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetchRegistry: true
